const DISCORD_INVITE='https://discord.gg/eySfvMJ';
const MAP_URL='https://allium-bluemap.wilson-bnj.workers.dev/';
function copyIP(){navigator.clipboard.writeText('play.alliummc.online');const e=document.getElementById('copyText');if(e){e.textContent='COPIED!';setTimeout(()=>e.textContent='COPY',1400)}}
const sectionInfo={content:['CONTENT MODS','Everything that adds actual content to the pack.'],client:['CLIENT-SIDE','Client-only performance, visual and QOL mods.'],dependencies:['DEPENDENCIES & LIBRARIES','Required by other mods. Not particularly exciting.'],server:['SERVER-SIDE','Server utilities, performance and administration.']};
function cleanFile(s){return s.replace(/\.jar$/i,'').replace(/[-_](?:neoforge|forge)?[-_]?(?:mc)?\d[\w.+-]*$/i,'').replace(/[-_]/g,' ').replace(/\s+/g,' ').trim()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tileContents(title,icon,desc,source='PROJECT'){return `<div class="mod-name">${esc(title)}</div><div class="mod-icon-wrap">${icon?`<img src="${esc(icon)}" alt="${esc(title)}" onerror="this.src='/assets/allium-flower.png'">`:`<img src="/assets/allium-flower.png" alt="">`}<div class="tip"><b>${esc(title)}</b><span>${esc(desc||'Project information unavailable.')}</span><em>VIEW ${esc(source)} ↗</em></div></div>`}
async function searchModrinth(el,name){try{const r=await fetch('https://api.modrinth.com/v2/search?limit=1&query='+encodeURIComponent(name));if(!r.ok)return false;const data=await r.json(),hit=data.hits&&data.hits[0];if(!hit)return false;el.href='https://modrinth.com/project/'+hit.project_id;el.dataset.title=hit.title;el.innerHTML=tileContents(hit.title,hit.icon_url,hit.description,'ON MODRINTH');return true}catch{return false}}
function highlightName(el,q){const n=el.querySelector('.mod-name');if(!n)return;const title=el.dataset.title||el.dataset.name||'';if(!q){n.textContent=title;return}const i=title.toLowerCase().indexOf(q.toLowerCase());if(i<0){n.textContent=title;return}n.innerHTML=esc(title.slice(0,i))+'<mark>'+esc(title.slice(i,i+q.length))+'</mark>'+esc(title.slice(i+q.length))}
function filterMods(){const input=document.getElementById('modSearch');if(!input)return;const q=input.value.trim();let shown=0,total=document.querySelectorAll('.mod-tile').length;document.querySelectorAll('.mod-section').forEach(sec=>{let sectionShown=0;sec.querySelectorAll('.mod-tile').forEach(el=>{const hay=(el.dataset.title+' '+el.dataset.name).toLowerCase();const ok=!q||hay.includes(q.toLowerCase());el.hidden=!ok;if(ok){shown++;sectionShown++}highlightName(el,q)});sec.hidden=!!q&&!sectionShown});const c=document.getElementById('modSearchCount');if(c)c.textContent=q?`${shown} of ${total} mods`:'';const empty=document.getElementById('modEmpty');if(empty){empty.hidden=shown!==0;empty.textContent=`No mods found for “${q}”.`}const clear=document.getElementById('clearModSearch');if(clear)clear.classList.toggle('visible',!!q)}
async function loadMods(){const root=document.getElementById('modSections');if(!root||!window.ALLIUM_MODS)return;const total=window.ALLIUM_MODS.length;const tc=document.getElementById('totalModCount');if(tc)tc.textContent=`${total} MODS`;for(const key of ['content','client','dependencies','server']){const mods=window.ALLIUM_MODS.filter(x=>x.section===key);const sec=document.createElement('div');sec.className='mod-section';sec.id=key;sec.innerHTML=`<div class="mod-head"><div><h3>${sectionInfo[key][0]}</h3><p>${sectionInfo[key][1]}</p></div><span class="mod-count">${mods.length} MODS</span></div><div class="mod-grid"></div>`;root.appendChild(sec);const grid=sec.querySelector('.mod-grid');for(const mod of mods){const name=cleanFile(mod.file),a=document.createElement('a');a.className='mod-tile';a.dataset.id=mod.id||'';a.dataset.name=name;a.dataset.title=name;a.href=mod.id?`https://modrinth.com/project/${mod.id}`:`https://modrinth.com/mods?q=${encodeURIComponent(name)}`;a.target='_blank';a.rel='noopener';a.innerHTML=tileContents(name,null,mod.id?'Loading project information…':'Looking for the project page…');grid.appendChild(a)}}const ids=[...new Set(window.ALLIUM_MODS.map(x=>x.id).filter(Boolean))];for(let i=0;i<ids.length;i+=50){try{const r=await fetch('https://api.modrinth.com/v2/projects?ids='+encodeURIComponent(JSON.stringify(ids.slice(i,i+50))));if(!r.ok)continue;for(const p of await r.json()){document.querySelectorAll(`.mod-tile[data-id="${CSS.escape(p.id)}"]`).forEach(el=>{el.href='https://modrinth.com/mod/'+p.slug;el.dataset.title=p.title;el.innerHTML=tileContents(p.title,p.icon_url,p.description,'ON MODRINTH')})}}catch(e){console.warn('Modrinth metadata failed',e)}}const unmatched=[...document.querySelectorAll('.mod-tile[data-id=""]')];for(const el of unmatched)await searchModrinth(el,el.dataset.name);filterMods()}
function setupModTools(){const input=document.getElementById('modSearch'),clear=document.getElementById('clearModSearch');if(input){input.addEventListener('input',filterMods);clear?.addEventListener('click',()=>{input.value='';filterMods();input.focus()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();input.focus()}if(e.key==='Escape'&&document.activeElement===input){input.value='';filterMods();input.blur()}})}}
function setupNav(){const path=location.pathname;document.querySelectorAll('.nav-links a').forEach(a=>{const h=a.getAttribute('href');if((path==='/'&&h==='/')||(path.startsWith('/download')&&h.includes('download'))||(path.startsWith('/map')&&h.includes('map'))||(location.hash.startsWith('#')&&h.includes('#mods')))a.classList.add('active')});const nav=document.querySelector('.nav-inner');if(nav&&!nav.querySelector('.mobile-toggle')){const b=document.createElement('button');b.className='mobile-toggle';b.setAttribute('aria-label','Toggle navigation');b.textContent='☰';b.onclick=()=>nav.classList.toggle('mobile-open');nav.insertBefore(b,nav.querySelector('.nav-links'))}}
async function loadLiveStats(){
  const heads=document.getElementById('playerHeads'),state=document.getElementById('serverState'),dot=document.getElementById('serverDot'),ver=document.getElementById('serverVersion');
  try{
    const controller=new AbortController();
    const timer=setTimeout(()=>controller.abort(),6000);
    const r=await fetch('https://api.mcstatus.io/v2/status/java/play.alliummc.online',{cache:'no-store',signal:controller.signal});
    clearTimeout(timer);
    if(!r.ok)throw new Error('Minecraft status request failed');
    const d=await r.json();
    const online=Number(d.players?.online||0),max=Number(d.players?.max||20),list=Array.isArray(d.players?.list)?d.players.list:[];
    if(state)state.textContent=d.online?'ONLINE':'OFFLINE';
    if(dot)dot.className='status-dot '+(d.online?'online':'offline');
    if(ver&&d.online)ver.textContent=`Minecraft ${d.version?.name_clean||'1.21.1'} · NeoForge`;
    if(heads){
      if(!d.online){heads.innerHTML='<strong>OFFLINE</strong>';}
      else if(list.length){
        const shown=list.slice(0,8);
        heads.innerHTML=shown.map(p=>{const name=p.name_clean||p.name_raw||'Player',id=p.uuid||name;return `<span class="player-head-wrap" tabindex="0" aria-label="${esc(name)}"><img src="https://api.mcskin.me/head/${encodeURIComponent(id)}?size=28" alt="" loading="lazy"><span class="player-head-tooltip" role="tooltip">${esc(name)}</span></span>`}).join('')+`<span class="player-total">${online} / ${max}</span>`;
      }else{
        heads.innerHTML=`<strong class="player-count-only">${online} / ${max}</strong>`;
        heads.title='The server is not exposing online player names.';
      }
    }
  }catch(e){
    if(state)state.textContent='UNKNOWN';
    if(dot)dot.className='status-dot unknown';
    if(heads){heads.innerHTML='<strong class="player-count-only">Unavailable</strong>';heads.title='Player count could not be loaded.'}
  }
  const dm=document.getElementById('discordMembers'),dol=document.getElementById('discordOnline');
  try{const r=await fetch('https://discord.com/api/v10/invites/eySfvMJ?with_counts=true');const d=await r.json();const members=d.approximate_member_count??'—',online=d.approximate_presence_count??'—';if(dm)dm.textContent=Number(members).toLocaleString?.()||members;if(dol)dol.textContent=`${Number(online).toLocaleString?.()||online} online`;document.querySelectorAll('.nav-socials a[title="Discord"]').forEach(a=>a.title=`Discord · ${members} members · ${online} online`)}catch{if(dm)dm.textContent='Unavailable';if(dol)dol.textContent='Discord'}
}
async function checkMap(){const dots=document.querySelectorAll('.map-dot'),mapNav=document.querySelector('.nav-links a[href="/map/"]');try{await fetch(MAP_URL,{mode:'no-cors',cache:'no-store'});dots.forEach(d=>d.className='status-dot map-dot online');if(mapNav)mapNav.classList.add('map-online');const t=document.getElementById('mapPageStatus');if(t)t.textContent='Live Season 13 world map'}catch{dots.forEach(d=>d.className='status-dot map-dot unknown');const t=document.getElementById('mapPageStatus');if(t)t.textContent='Map status unavailable'}}
function setupBackToTop(){const b=document.createElement('button');b.id='backToTop';b.className='back-to-top';b.textContent='↑ TOP';b.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.body.appendChild(b);const f=()=>b.classList.toggle('visible',scrollY>900);addEventListener('scroll',f,{passive:true});f()}
document.addEventListener('DOMContentLoaded',async()=>{setupNav();setupModTools();await loadMods();loadLiveStats();checkMap();setupBackToTop();document.querySelectorAll('code').forEach(c=>{if(c.textContent.trim()==='play.alliummc.online'){c.classList.add('click-copy');c.title='Click to copy';c.addEventListener('click',copyIP)}})});

const HERO_SLIDES=['/assets/hero/season13-1.webp','/assets/hero/season13-2.webp','/assets/hero/season13-3.webp','/assets/hero/season13-4.webp','/assets/hero/season13-5.webp','/assets/hero/season13-6.webp'];
function setupHeroSlideshow(){const img=document.getElementById('heroSlide'),link=document.querySelector('.hero-slideshow');if(!img)return;let i=0;setInterval(()=>{img.classList.add('fading');setTimeout(()=>{i=(i+1)%HERO_SLIDES.length;img.src=HERO_SLIDES[i];if(link)link.href=HERO_SLIDES[i];img.classList.remove('fading')},650)},5000)}
function updateAlliumAge(){const start=new Date(2019,5,6),now=new Date();const realDays=Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate())-start)/86400000);let y=now.getFullYear()-2019,m=now.getMonth()-5,d=now.getDate()-6;if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}const age=document.getElementById('alliumAge'),extra=document.getElementById('alliumAgeExtra');if(age)age.textContent=`${y}Y · ${m}M · ${d}D`;if(extra)extra.innerHTML=`<span>${realDays.toLocaleString()} real days</span><span>${(realDays*72).toLocaleString()} Minecraft days</span>`}
function setupArchiveCard(){const img=document.getElementById('archiveImage'),cap=document.getElementById('archiveCaption');if(!img)return;const shots=[...document.querySelectorAll('.history-shot img')];const known=['/assets/history/2019-06-11_22.49.29.webp','/assets/history/2020-04-05_20.34.51.webp','/assets/history/2021-12-30_16.25.46.webp','/assets/history/2022-09-30_19.35.35.webp','/assets/history/2024-06-21_12.00.45.webp','/assets/history/2025-06-29_20.29.13.webp'];const src=known[Math.floor(Math.random()*known.length)];img.src=src;const name=src.split('/').pop().replace('.webp','').replaceAll('_',' ');if(cap)cap.textContent=`${name} · Open the full seven-year chronicle →`}
function setupHistoryLightbox(){const links=[...document.querySelectorAll('.history-lightbox-link')],lb=document.getElementById('historyLightbox');if(!links.length||!lb)return;const img=document.getElementById('lightboxImage'),cap=document.getElementById('lightboxCaption');let i=0;const show=n=>{i=(n+links.length)%links.length;img.src=links[i].href;cap.textContent=links[i].dataset.caption||'';lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};const close=()=>{lb.classList.remove('open');lb.setAttribute('aria-hidden','true');document.body.style.overflow=''};links.forEach((a,n)=>a.addEventListener('click',e=>{e.preventDefault();show(n)}));lb.querySelector('.lightbox-close').onclick=close;lb.querySelector('.lightbox-prev').onclick=()=>show(i-1);lb.querySelector('.lightbox-next').onclick=()=>show(i+1);lb.addEventListener('click',e=>{if(e.target===lb)close()});addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')show(i-1);if(e.key==='ArrowRight')show(i+1)})}
function setupHistoryIndicator(){const sections=[...document.querySelectorAll('.era[id]')],links=[...document.querySelectorAll('.history-nav a')];if(!sections.length)return;const update=()=>{let cur=sections[0].id;for(const s of sections)if(s.getBoundingClientRect().top<180)cur=s.id;links.forEach(a=>a.classList.toggle('current',a.getAttribute('href')==='#'+cur))};addEventListener('scroll',update,{passive:true});update()}
document.addEventListener('DOMContentLoaded',()=>{setupHeroSlideshow();updateAlliumAge();setupArchiveCard();setupHistoryLightbox();setupHistoryIndicator();const c=document.getElementById('copyText');if(c)c.addEventListener('click',()=>{c.textContent='COPIED ✓';c.classList.add('copied');setTimeout(()=>{c.textContent='COPY';c.classList.remove('copied')},1600)})});
